<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseSport" Class="DataClassesSportDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DatabaseSport.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="PK_09_TabelaLigowa.Properties.Settings" SettingsPropertyName="DatabaseSportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamHostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeamGuestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoalHost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoalGuest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Team_Match" Member="Team" ThisKey="TeamGuestId" OtherKey="Id" Type="Team" IsForeignKey="true" />
      <Association Name="Team_Match1" Member="Team1" ThisKey="TeamHostId" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Team_Match" Member="Matches" ThisKey="Id" OtherKey="TeamGuestId" Type="Match" />
      <Association Name="Team_Match1" Member="Matches1" ThisKey="Id" OtherKey="TeamHostId" Type="Match" />
    </Type>
  </Table>
</Database>